[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "_site"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"